FROM {{ARG_FROM}}

ENV CGO_ENABLED=0
WORKDIR /home/go/src/hkjn.me/uploader/
COPY ["vendor", "./vendor/"]
COPY ["*.go", "./"]
VOLUME ["/build"]
RUN go test && \
    go vet && \
    go build

CMD ["mv", "-v", "uploader", "/build/"]

